### ISSUE TITLE
单击任意位置都能关闭新增知识库窗口

### ISSUE THREAD

**Issue by qiu432503** [xueyukeji/knowledgebase#1]
操作步骤

1、单击添加知识库，弹出窗口

2、点击任意位置，都能关闭新增知识库窗口

截取图片

![image](https://user-images.githubusercontent.com/32641177/31340224-0eaef7d6-ad38-11e7-805b-d3e15a66d590.png)

**Comment by nieying** [comment]
所有弹出框点击任意位置都改了

**Comment by qiu432503** [comment]
已确认修复，关闭
