### ISSUE TITLE
新增的知识条目页面，提示每项都为必填项，如果没填写的，要提示

### ISSUE THREAD

**Issue by qiu432503** [xueyukeji/knowledgebase#17]
操作步骤

1、进入到新增的知识条目页面，每项提示都为必填项 ，包括选择附件

2、标签，一级标签和二级标签为必填项

截取图片

![image](https://user-images.githubusercontent.com/32641177/31367179-0a8656b6-ada8-11e7-8ce7-23620a4af749.png)

**Comment by nieying** [comment]
重复bug, 已经修复了
@qiu432503
