### ISSUE TITLE
主导航栏没有 我的贡献 功能选项，（我的贡献页面包含新增知识条目、修改知识条目、删除知识条目）

### ISSUE THREAD

**Issue by qiu432503** [xueyukeji/knowledgebase#18]
![image](https://user-images.githubusercontent.com/32641177/31367279-c095cd92-ada8-11e7-859f-34cbbc243ae2.png)

**Comment by soakit** [comment]
二期需求

**Comment by qiu432503** [comment]
那新建的知识条目可以修改和删除吗

**Comment by qiu432503** [comment]
二期功能，关闭
