### ISSUE TITLE
新增标签功能，管理标签窗口，没有

### ISSUE THREAD

**Issue by qiu432503** [xueyukeji/knowledgebase#19]
![image](https://user-images.githubusercontent.com/32641177/31367637-38a5cd26-adab-11e7-82b1-2c5395271d6d.png)

**Comment by soakit** [comment]
是同一个，改名为管理标签

**Comment by nieying** [comment]
字已经改过来了

**Comment by qiu432503** [comment]
已确认修复，关闭bug
