### ISSUE TITLE
未输入知识库名称也能新建知识库成功

### ISSUE THREAD

**Issue by qiu432503** [xueyukeji/knowledgebase#2]
操作步骤

1、单击添加知识库，弹出窗口

2、未输入知识库名称，也能新建成功

预期结果

未输入名称，确认按钮不可点击

截取图片

![image](https://user-images.githubusercontent.com/32641177/31340355-75f1803a-ad38-11e7-97f3-813f8b22087c.png)

**Comment by soakit** [comment]
已解决， @qiu432503 测下

**Comment by qiu432503** [comment]
已确认修复，关闭
