### ISSUE TITLE
新增知识条目页面，标题和、描述没有长度限制（太长会报错）

### ISSUE THREAD

**Issue by qiu432503** [xueyukeji/knowledgebase#20]
![image](https://user-images.githubusercontent.com/32641177/31367735-d63d24f8-adab-11e7-9a0d-6611b1c45d75.png)

**Comment by nieying** [comment]
标题限制32个字符，描述限制500个字符，跟肖敏确定过了

**Comment by qiu432503** [comment]
已确认修复，关闭bug
