### ISSUE TITLE
普通用户新建知识条目，没有显示标签

### ISSUE THREAD

**Issue by qiu432503** [xueyukeji/knowledgebase#21]
![image](https://user-images.githubusercontent.com/32641177/31367926-0b725c3c-adad-11e7-9b5d-8427a308afb4.png)

**Comment by soakit** [comment]
确认下这个知识库下是否有标签？

**Comment by qiu432503** [comment]
有，所有的知识库都是这个标签

**Comment by nieying** [comment]
知识库默认选中当前的

**Comment by qiu432503** [comment]
嗯，有些知识库，没有新建标签，也有标签

**Comment by qiu432503** [comment]
已确认修复，关闭bug
