### ISSUE TITLE
ie浏览器，在共享空间或群组空间位置切换到知识库页面，提示未找到

### ISSUE THREAD

**Issue by qiu432503** [xueyukeji/knowledgebase#29]
操作步骤

1、登录云盘进去，默认进入到个人空间，

2、单击共享空间或群组空间导航进去到共享空间根目录

3、单击 知识库，进去，显示未找到

截取图片

![image](https://user-images.githubusercontent.com/32641177/31418297-d8481cbe-ae67-11e7-87ec-5d1fcc7f010a.png)

**Comment by soakit** [comment]
待上测试环境测试

**Comment by qiu432503** [comment]
已确认修复，关闭bug
