### ISSUE TITLE
知识库跳转选项，添加滚动条 窗口做下自适应

### ISSUE THREAD

**Issue by qiu432503** [xueyukeji/knowledgebase#3]
操作步骤

1、添加多个知识库后，最后的知识库点击不到，知识库管理选项也自动屏蔽了

2、窗口做下自适应

截取图片

![image](https://user-images.githubusercontent.com/32641177/31341506-38758338-ad3c-11e7-8c3a-f16fb823a0ca.png)

**Comment by soakit** [comment]
滚动条已加
自适应 增强?

**Comment by nieying** [comment]
第一点已经解决了 @pengxueshan

**Comment by qiu432503** [comment]
已确认修复，关闭bug
