### ISSUE TITLE
【前端】标签搜索后，切换到其他知识库，显示没有内容

### ISSUE THREAD

**Issue by qiu432503** [xueyukeji/knowledgebase#32]
操作步骤

1、单击标签，标签名称进入到搜索栏，搜索，切换到其他知识库，暂无数据内容
前提是有数据的

截取图片

![image](https://user-images.githubusercontent.com/32641177/31476743-a543f0d0-af3a-11e7-8411-47c4b518f51b.png)

**Comment by soakit** [comment]
已修复

**Comment by jiuyuehe** [comment]
ok
