### ISSUE TITLE
知识库列表标签搜索条件修改, 改成和京东的搜索一样

### ISSUE THREAD

**Issue by luckyufei** [xueyukeji/knowledgebase#37]
## 解决了什么问题
解决将多类标签平铺显示, 方便用户快速搜索的问题

## 建议最终实现效果（如可能需提供API等信息）
实现效果大体如下
![default](https://user-images.githubusercontent.com/773187/31572139-8adc29f8-b064-11e7-938d-1ed072649eef.png)

**Comment by soakit** [comment]
已merge到master
