### ISSUE TITLE
新增知识条目页面，要能返回到上一级，要显示明确的路径

### ISSUE THREAD

**Issue by qiu432503** [xueyukeji/knowledgebase#4]
操作步骤

1、单击某个知识库进去

2、点击新增知识条目，进去后，不能返回到上一级，也没有显示明确的路径

截取图片

![image](https://user-images.githubusercontent.com/32641177/31341727-fe9f634e-ad3c-11e7-9813-dc029da511e0.png)

**Comment by nieying** [comment]
之前设计图没有，已加上去
@qiu432503
