### ISSUE TITLE
新增知识条目bug

### ISSUE THREAD

**Issue by jiuyuehe** [xueyukeji/knowledgebase#41]
标签 还是只能添加一级标签和二级标签

应该都是选择二级标签

![image](https://user-images.githubusercontent.com/4385903/31800668-0ad1d148-b575-11e7-9e20-f64f1007ffce.png)

**Comment by jiuyuehe** [comment]
知识条目列表，未按最近更新排列

![image](https://user-images.githubusercontent.com/4385903/31800744-8e3d70e6-b575-11e7-80a2-02daa408eeac.png)

**Comment by soakit** [comment]
修复完成
