### ISSUE TITLE
新增标签无效

### ISSUE THREAD

**Issue by qiu432503** [xueyukeji/knowledgebase#5]
操作步骤

1、单击某个知识库进去

2、点击新增标签

3、输入名称，点击确认，新建无效

截取图片

![image](https://user-images.githubusercontent.com/32641177/31341772-300c52fc-ad3d-11e7-8a12-1e778064151b.png)

**Comment by soakit** [comment]
已解决 @qiu432503

**Comment by qiu432503** [comment]
已修复，关闭
