### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by jiuyuehe** [xueyukeji/knowledgebase#58]
1： 知识条目中的共享者，能显示该贡献者在这个知识库里的所有知识条。（不做）

2：设置用户页面，需要显示组织架构。因为几十所学校，管理员并不清楚是哪些老师属于那个学校；（3期做）

3： 系统标签选择多个，目前只能选择两个系统标签， 修改为系统标签 为非必填项，也能填写多个，不做限制；还是每个大类选择一个（不做）

**Comment by nieying** [comment]
设置专家，设置用户页面修改
![791508835174_ pic_hd](https://user-images.githubusercontent.com/8042574/31933506-e9bce612-b86e-11e7-9bb7-f7e7a111c4a7.jpg)
