### ISSUE TITLE
进入知识库页面，没有显示用户信息

### ISSUE THREAD

**Issue by qiu432503** [xueyukeji/knowledgebase#6]
操作步骤

1、登录系统管理员账号，单击知识库，

2、知识库太多，没有显示用户信息

截取图片

![image](https://user-images.githubusercontent.com/32641177/31344198-9242eff6-ad44-11e7-9330-8b56e76cc704.png)

**Comment by soakit** [comment]
设计稿里有头像

**Comment by nieying** [comment]
滚动条定制下， @allanfish 提供下
滚动区域不应该包含下面的用户信息区。

**Comment by qiu432503** [comment]
已确认修复，关闭bug
