### ISSUE TITLE
审批页面与设计完全不符

### ISSUE THREAD

**Issue by jiuyuehe** [xueyukeji/knowledgebase#64]
![image](https://user-images.githubusercontent.com/4385903/32144113-c99b67c6-bcee-11e7-9c1b-f9ffbac15a67.png)

**Comment by nieying** [comment]
已修改
![image](https://user-images.githubusercontent.com/8042574/32173562-74d6c9ba-bd4d-11e7-8aa5-db9e6dad9c62.png)
