### ISSUE TITLE
用户贡献的文件，已经审批通过的文件，不能下载

### ISSUE THREAD

**Issue by qiu432503** [xueyukeji/knowledgebase#69]
![image](https://user-images.githubusercontent.com/32641177/32154129-8a997eca-bd69-11e7-818e-db98b2dfddc0.png)

**Comment by soakit** [comment]
这个是下载数。
详情页会加个下载按钮。

**Comment by nieying** [comment]
已经修改好了
下载
![image](https://user-images.githubusercontent.com/8042574/32171714-1b201cb0-bd47-11e7-82c8-da8691504b23.png)
查看数
![image](https://user-images.githubusercontent.com/8042574/32171737-2cb0185e-bd47-11e7-8198-ab199d8462b3.png)
