### ISSUE TITLE
预览以后，次数未增加

### ISSUE THREAD

**Issue by jiuyuehe** [xueyukeji/knowledgebase#71]
![image](https://user-images.githubusercontent.com/4385903/32170832-2f34c86c-bdb1-11e7-978c-b3b885cd2796.png)

**Comment by nieying** [comment]
已经修复
查看数我们是这样计算，点击条目一次查看数增加1
下载数是在条目详情增加一个文件下载的按钮，下载一次，下载数增加1

**Comment by jiuyuehe** [comment]
我的贡献里面，次数显示都为0
